# Generated by Django 6.0.7 on 2026-07-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_role_options_remove_role_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
    ]
