# Generated by Django 6.0.7 on 2026-08-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customeraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Rabbit', 'Rabbit'), ('Fish', 'Fish'), ('Other', 'Other')], default='Dog', max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('health_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='accounts.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
