# Generated by Django 6.0.7 on 2026-08-10 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Medicine', 'Medicine'), ('Supplement', 'Supplement'), ('Food', 'Food'), ('Treat', 'Treats'), ('Grooming', 'Grooming'), ('Hygiene', 'Hygiene'), ('FleaTick', 'Flea & Tick Control'), ('Deworming', 'Deworming'), ('DentalCare', 'Dental Care'), ('SkinCare', 'Skin Care'), ('JointCare', 'Joint & Bone Care'), ('Vitamins', 'Vitamins'), ('Accessories', 'Pet Accessories'), ('Toys', 'Toys'), ('Beds', 'Beds & Furniture'), ('Leashes', 'Leashes & Collars'), ('Clothing', 'Pet Clothing'), ('Feeding', 'Feeding Supplies'), ('Aquarium', 'Aquarium Supplies'), ('BirdCare', 'Bird Care'), ('FarmSupplies', 'Farm Supplies'), ('VetEquipment', 'Veterinary Equipment'), ('Other', 'Other')], default='Other', max_length=30),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_ingredient', models.CharField(blank=True, max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('dosage_form', models.CharField(blank=True, max_length=100)),
                ('prescription_required', models.BooleanField(default=False)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('storage_instructions', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField(blank=True)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('form', models.CharField(blank=True, max_length=100)),
                ('flavor', models.CharField(blank=True, max_length=100)),
                ('age_group', models.CharField(blank=True, max_length=100)),
                ('weight_range', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('storage_instructions', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplement', to='products.product')),
            ],
        ),
    ]
